export const Sessions = [
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class! Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'pending',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 24.32
        },
        gender: 'Man'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'resolved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'resolved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'resolved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'resolved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment.",
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    }, {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAnr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    {
        status: 'disputeAr',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07 ',
        meetingTime: '7:00AM',
        meetingDuration: '60',
        course: 'ECON ECON 101',
        avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
        isOnline: false,
        ratings: 2.6,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman',
        disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        disputeMessage: "After review of the case, we have decided to refund the student their initial payment."
    },
    // {
    //     status: 'disputeAnr',
    //     session: 'Econ 101 class with Aaron Tomandl',
    //     profileName: 'Ashley Jane',
    //     message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
    //     meetingLocation: {
    //         name: "Andrew's Zoom Room",
    //         url: "zoom.us",
    //         type: 'in-person'
    //     },
    //     meetingDate: 'TUE 17.07 ',
    //     meetingTime: '7:00AM',
    //     meetingDuration: '60',
    //     course: 'ECON ECON 101',
    //     avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
    //     isOnline: false,
    //     ratings: 2.6,
    //     subject: 'Economics and Math',
    //     amount: 24.32,
    //     payment: {
    //         method: 'visa',
    //         info: 'MsterCard••••9905',
    //         expDate: '06/26',
    //         price: 4562
    //     },
    //     disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!"
    // },
    // {
    //     status: 'disputeAnr',
    //     session: 'Econ 101 class with Aaron Tomandl',
    //     profileName: 'Ashley Jane',
    //     message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
    //     meetingLocation: {
    //         name: "Andrew's Zoom Room",
    //         url: "zoom.us",
    //         type: 'in-person'
    //     },
    //     meetingDate: 'TUE 17.07 ',
    //     meetingTime: '7:00AM',
    //     meetingDuration: '60',
    //     course: 'ECON ECON 101',
    //     avatar: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=200',
    //     isOnline: false,
    //     ratings: 2.6,
    //     subject: 'Economics and Math',
    //     amount: 24.32,
    //     payment: {
    //         method: 'visa',
    //         info: 'MsterCard••••9905',
    //         expDate: '06/26',
    //         price: 4562
    //     },
    //     disputeReason: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!"
    // },

]

export const ScheduleData = [
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
    {
        status: 'approved',
        session: 'Econ 101 class with Aaron Tomandl',
        profileName: 'Ashley Jane',
        message: "Hello! I've heard a lot about your excellent course. I like your approach to work and your attention to each student. I'm looking forward to our first class!",
        meetingLocation: [
            { label: "Andrew's Zoom Room", value: "zoom.us", type: 'in-person', selected: true },
            { label: "Dmytro zoom room", value: "google.com", type: 'in-person', selected: false },
            { label: "Andrew", value: "skype", type: 'virtual', selected: false },
            { label: "Google meeting", value: "slack.com", type: 'virtual', selected: false },
        ],
        meetingDate: 'TUE 17.07',
        meetingTime: '2:00PM',
        meetingDuration: '9999',
        course: 'ECON 101',
        avatar: 'https://i.pravatar.cc/200',
        isOnlne: true,
        ratings: 3.7,
        subject: 'Economics and Math',
        amount: 24.32,
        payment: {
            method: 'visa',
            info: 'MsterCard••••9905',
            expDate: '06/26',
            price: 4562
        },
        gender: 'Woman'
    },
]